<link
    href="{{ asset('frontend/img/apple-touch-icon.png') }}"
    rel="apple-touch-icon"
/>
<link href="{{ asset('css/app.css') }}" rel="stylesheet" />
<link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.2/css/bootstrap-select.min.css"
/>
<link
    rel="stylesheet"
    href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,300;0,500;0,700;1,400&display=swap"
/>
<link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
/>
<link
    rel="stylesheet"
    href="{{
        asset('vendors/OwlCarousel2-2.3.4/dist/assets/owl.carousel.min.css')
    }}"
/>
<link
    rel="stylesheet"
    href="{{
        asset(
            'vendors/OwlCarousel2-2.3.4/dist/assets/owl.theme.default.min.css'
        )
    }}"
/>
